---
-on:
  pull_request:
    branches:
      - develop
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - name: setup jdk
              uses: actions/setup-java@v2
              with:
                disrtibution: 'temurin'
                java-version: '17'
            
            -name: maven package
              run: mvn clean  package

            -name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: java-app

            -name: deploy to server
              needs: build
              runs-on: ubuntu-latest

              steps:
                -name:download artifact
                  uses: actions/download-artifact@v2
                  with:
                    name: java-app

                -name: create ssh key
                  run: |
                    mkdir -p ~/.ssh
                    echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa

                -name: create directory on server
                  run : ssh -o StrictHostKeyChecking=no|
                    ${{ secrets.VM_USER }}@${{ secrets.vm_HOST }} "mkdir -p /home/${{ secrets.VM_USER }}/app"

                -name: copy artifact to server
                run: scp -o StrictHostKeyChecking=no target/*.war ${{ secrets.VM_USER }}@${{ secrets.vm_HOST }}:/home/${{ secrets.VM_USER }}/app

                -name: restart server
                run:   
                    ssh -o StrictHostKeyChecking=no \
                    -i ~/.ssh/id_rsa \
                     ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
                     "pkill -f java || true && \
                      cd /home/${{ secrets.VM_USER }}/app && \
                      nohup java -jar *.jar > app.log 2>&1 &"
              


        
        
      
